name: Build base with dependencies
# Builds the Storm basesystem Docker images with dependencies and deploys them to Dockerhub

on:
  # needed to trigger the workflow manually
  workflow_dispatch:

jobs:
  buildDistro:
    name: Build dependencies (${{ matrix.config.buildType }}, Carl ${{ matrix.config.carlTag }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - {tag: "latest", carlTag: "14.28", buildType: "Release"}
          - {tag: "latest-debug", carlTag: "14.28-debug", buildType: "Debug"}

    steps:
      - name: Git clone
        uses: actions/checkout@v4
      - name: Build from Dockerfile
        run: docker build -f storm-dependencies/Dockerfile -t movesrwth/storm-dependencies:${{ matrix.config.tag }} . --build-arg BASE_IMAGE=movesrwth/carl-storm:${{ matrix.config.carlTag }}
      - name: Login to Docker Hub
        # Only login if using original repo
        if: github.repository_owner == 'moves-rwth'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.STORM_CI_DOCKER_USERNAME }}
          password: ${{ secrets.STORM_CI_DOCKER_TOKEN }}
      - name: Deploy image
        # Only deploy if using original repo
        if: github.repository_owner == 'moves-rwth'
        run: |
          docker push movesrwth/storm-dependencies:${{ matrix.config.tag }}
