name: Build base with dependencies
# Builds the Storm basesystem Docker images with dependencies and deploys them to Dockerhub
# Build is distributed across multiple runners based on:
# https://docs.docker.com/build/ci/github-actions/multi-platform/#distribute-build-across-multiple-runners

on:
  # needed to trigger the workflow manually
  workflow_dispatch:

env:
  IMAGE: movesrwth/storm-dependencies
  # GitHub runners currently have 4 cores
  NR_JOBS: "4"

jobs:
  build:
    name: Build ${{ matrix.image.name }} on ${{ matrix.platform.name }}
    runs-on: ${{ matrix.platform.runner }}
    strategy:
      matrix:
        image:
          - {name: "latest",
             baseImg: "movesrwth/carl-storm:stable",
             file: "storm-dependencies/Dockerfile"
            }
          - {name: "latest-debug",
             baseImg: "movesrwth/carl-storm:stable-debug",
             file: "storm-dependencies/Dockerfile"
            }
        platform:
          - {name: linux/amd64, runner: "ubuntu-latest"}
          - {name: linux/arm64, runner: "ubuntu-24.04-arm"}
    steps:
      - name: Prepare
        # Sanitize platform name
        run: |
          platform=${{ matrix.platform.name }}
          echo "PLATFORM=${platform//\//-}" >> $GITHUB_ENV
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,${{ matrix.image.name }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to Docker Hub
        # Only login if using original repo
        if: github.repository_owner == 'moves-rwth'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.STORM_CI_DOCKER_USERNAME }}
          password: ${{ secrets.STORM_CI_DOCKER_TOKEN }}
      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        with:
          file: ${{ matrix.image.file }}
          # Set build arguments
          build-args: |
            BASE_IMAGE=${{ matrix.image.baseImg }}
            no_threads=${{ env.NR_JOBS }}
          platforms: ${{ matrix.platform.name }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=${{ env.IMAGE }},push-by-digest=true,name-canonical=true,push=true
      - name: Export digest
        run: |
          mkdir -p ${{ runner.temp }}/digests/${{ matrix.image.name }}
          digest="${{ steps.build.outputs.digest }}"
          touch "${{ runner.temp }}/digests/${{ matrix.image.name }}/${digest#sha256:}"
      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.image.name }}-digests-${{ env.PLATFORM }}
          path: ${{ runner.temp }}/digests/${{ matrix.image.name }}/*
          if-no-files-found: error
          retention-days: 1

  merge:
    name: Merge manifests for ${{ matrix.image.name }}
    runs-on: ubuntu-latest
    needs:
      - build
    strategy:
      matrix:
        image:
          # Must be the same as above
          - {name: "latest"}
          - {name: "latest-debug"}
    steps:
      - name: Download digests
        uses: actions/download-artifact@v4
        with:
          path: ${{ runner.temp }}/digests/${{ matrix.image.name }}
          pattern: ${{ matrix.image.name }}-digests-*
          merge-multiple: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.IMAGE }}
          tags: |
            type=raw,${{ matrix.image.name }}
      - name: Login to Docker Hub
        # Only login if using original repo
        if: github.repository_owner == 'moves-rwth'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.STORM_CI_DOCKER_USERNAME }}
          password: ${{ secrets.STORM_CI_DOCKER_TOKEN }}
      - name: Create manifest list and push
        working-directory: ${{ runner.temp }}/digests/${{ matrix.image.name }}
        run: |
          docker buildx imagetools create $(jq -cr '.tags | map("-t " + .) | join(" ")' <<< '${{ steps.meta.outputs.json}}') \
            $(printf '${{ env.IMAGE }}@sha256:%s ' *)
      - name: Inspect image
        run: |
          docker buildx imagetools inspect ${{ env.IMAGE }}:${{ steps.meta.outputs.version }}
